### ISSUE TITLE
Android Studio's logcat not recognized

### ISSUE THREAD

**Issue by codezjx** [leesei/logcat.tmLanguage#3]
By default, `Android Studio`'s logcat format is **threadtime**, and slightly different from the log of the 
`adb logcat` console output. So the regular expression does not match properly, which makes it not recognized.

`Android Studio`‘s logcat:
```
2020-03-19 20:45:58.981 788-883/system_process E/WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2020-03-19 20:45:59.040 599-599/? I/Proximity: distance = 1
2020-03-19 20:45:59.439 599-599/? I/chatty: uid=1000(system) sensors@1.0-ser identical 2 lines
2020-03-19 20:45:59.640 599-599/? I/Proximity: distance = 1
2020-03-19 20:45:59.662 606-606/? I/thermal_repeater: socket -1
2020-03-19 20:45:59.840 599-599/? I/Proximity: distance = 1
2020-03-19 20:46:00.001 788-865/system_process V/AlarmManager: Checking for alarms... rtc=1584621960001, elapsed=2030311086
2020-03-19 20:46:00.001 788-865/system_process V/AlarmManager: Triggering alarm #0: Alarm{600134a type 3 when 2030311086 android}
2020-03-19 20:46:00.002 788-865/system_process E/MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
2020-03-19 20:46:00.002 788-865/system_process W/System.err: java.lang.NullPointerException: null receiver
2020-03-19 20:46:00.002 788-865/system_process W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-19 20:46:00.002 788-865/system_process W/System.err:     at com.mediatek.server.MtkDataShaping.openLteGateByDataShaping(MtkDataShaping.java:36)
2020-03-19 20:46:00.002 788-865/system_process W/System.err:     at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3607)
2020-03-19 20:46:00.002 788-865/system_process W/System.err:     at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:3785)
2020-03-19 20:46:00.002 788-865/system_process V/AlarmManager: sending alarm Alarm{600134a type 3 when 2030311086 android}
2020-03-19 20:46:00.003 788-865/system_process D/AlarmManager: mBroadcastRefCount -> 1
2020-03-19 20:46:00.003 22124-22124/? I/ADB_SERVICES: local_socket_flush_outgoing read_data=10661
```

**Comment by codezjx** [comment]
I have submitted a PR for this issue. #4
